# Generated by Django 5.2.8 on 2025-11-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
